// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.560
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Landing() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<article class=\"flex flex-col gap-6\" id=\"home\"><h1 class=\"text-xl font-semibold\">Absolutely nothing to see here so quickly get in.</h1><div><button class=\"rounded border border-black p-1\" hx-get=\"/login-form\" hx-swap=\"outerHTML\" hx-target=\"#home\">Login</button> <button class=\"rounded border border-black p-1 bg-blue-400\" hx-swap=\"outerHTML\" hx-target=\"#home\" hx-get=\"/signup-form\">Signup</button></div></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout(nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func LoginForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section><a class=\"font-lg font-semibold hover:underline\" href=\"/\">Back</a><form class=\"flex flex-col items-center gap-4\" hx-post=\"/login\" hx-trigger=\"submit\" hx-swap=\"none\"><div class=\"flex flex-col\"><label for=\"username\">Username</label> <input class=\"rounded border border-black p-1\" id=\"username\" name=\"username\" rows=\"1\" cols=\"20\"></div><div class=\"flex flex-col\"><label for=\"password\">Password</label> <input class=\"rounded border border-black p-1\" id=\"password\" name=\"password\" rows=\"1\" cols=\"20\"></div><input class=\"rounded border border-black bg-blue-400 p-1\" type=\"submit\" value=\"Login\"></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func SignupForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section><a class=\"font-lg font-semibold hover:underline\" href=\"/\">Back</a><form class=\"flex flex-col items-center gap-4\" hx-post=\"/signup\" hx-trigger=\"submit\" hx-swap=\"none\"><div class=\"flex flex-col\"><label for=\"email\">Email</label> <input class=\"rounded border border-black p-1\" id=\"email\" name=\"email\" rows=\"1\" cols=\"20\"></div><div class=\"flex flex-col\"><label for=\"username\">Username</label> <input class=\"rounded border border-black p-1\" id=\"username\" name=\"username\" rows=\"1\" cols=\"20\"></div><div class=\"flex flex-col\"><label for=\"password\">Password</label> <input class=\"rounded border border-black p-1\" id=\"password\" name=\"password\" rows=\"1\" cols=\"20\"></div><input class=\"rounded border border-black bg-blue-400 p-1\" type=\"submit\" value=\"Signup\"></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
